services:
  mlserver:
    build:
      context: ./
      dockerfile: ./mlserver/Dockerfile
    image: mlserver
    expose:
      - 5001
    environment:
      - MODEL_NAME=triplet_model
    volumes:
      - ./mlruns:/mlruns # Optional

  webapp:
    build:
      context: ./
      dockerfile: ./webapp/Dockerfile
    image: webapp
    ports:
      - "8000:8000"
    environment:
      - MLSERVER_URL=mlserver
      - FLASK_APP=/webapp/app.py
    volumes:
      - ./data/drawings.geojson:/data/drawings.geojson # Optional
