name: build, test and push images

on:
  push:
    branches: [main]
    paths:
      - "countryguess/**"
      - "mlserver/**"
      - "webapp/**"
      - "data/reference/**"
      - "mlruns/0/**"
      - "mlruns/models/default/**"
      - "docker-compose.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images with cache
        run: |
          docker buildx bake \
          --file docker-compose.yml \
          --file .github/docker-compose-cache.json

      - name: Run containers and wait for health checks
        run: docker compose up -d --wait

      - name: Push images
        run: docker compose push

      - name: Cleanup
        if: always()
        run: docker compose down --remove-orphans
