name: Build and Push Docker Images

on:
  push:
    branches: [main]
    paths:
      - "countryguess/**"
      - "mlserver/**"
      - "webapp/**"
      - "data/reference/**"
      - "mlruns/0/**"
      - "mlruns/models/default/**"
      - "docker-compose.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push mlserver
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./mlserver/Dockerfile
          push: true
          tags: ghcr.io/country-guess-mlserver:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push webapp
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./webapp/Dockerfile
          push: true
          tags: ghcr.io/country-guess-webapp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
