name: build and test images

on:
  push:
    branches: [main]
    paths:
      - "countryguess/**"
      - "mlserver/**"
      - "webapp/**"
      - "data/reference/**"
      - "mlruns/0/**"
      - "mlruns/models/default/**"
      - "docker-compose.yml"

jobs:
  build:
    runs-on: ubuntu-minimal
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@main
        with:
          android: true
          haskell: true
          docker-images: false

      - name: Pull existing images
        run: docker compose pull || true

      - name: Build images, run containers and wait for health status
        run: docker compose up -d --build --wait

      - name: Push images
        run: docker compose push

      - name: Cleanup
        if: always()
        run: docker compose down --remove-orphans
