name: run end-to-end test

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "countryguess/**"
      - "mlserver/**"
      - "webapp/**"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mlserver/requirements.txt
          pip install -r webapp/requirements.txt

      - name: Start ML server
        env:
          MODEL_NAME: triplet_model
        run: |
          python -m mlserver.serve &
          # Wait for server to start
          timeout 20 bash -c 'until curl -s http://localhost:5001/health; do sleep 1; done'

      - name: Start webapp
        env:
          MLSERVER_URL: http://localhost:5001/predict
        run: |
          python -m webapp.app &
          # Wait for webapp to start
          timeout 20 bash -c 'until curl -s http://localhost:5002/health; do sleep 1; done'

      - name: Run end-to-end tests
        run: python -m unittest tests/test_e2e.py -v
